name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: nix fmt .
  tests:
    needs: nixfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: nix run ./tests#run .
